#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Passport.DataClasses
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="PassportDB")]
	public partial class EmbassyDataDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InsertCustomer(Customer instance);
    partial void UpdateCustomer(Customer instance);
    partial void DeleteCustomer(Customer instance);
    partial void InsertCustomerFile(CustomerFile instance);
    partial void UpdateCustomerFile(CustomerFile instance);
    partial void DeleteCustomerFile(CustomerFile instance);
    partial void InsertFamily(Family instance);
    partial void UpdateFamily(Family instance);
    partial void DeleteFamily(Family instance);
    partial void InsertKin(Kin instance);
    partial void UpdateKin(Kin instance);
    partial void DeleteKin(Kin instance);
    partial void InsertOpr(Opr instance);
    partial void UpdateOpr(Opr instance);
    partial void DeleteOpr(Opr instance);
    #endregion
		
		public EmbassyDataDataContext() : 
				base(global::Passport.Properties.Settings.Default.PassportDBConnectionString3, mappingSource)
		{
			OnCreated();
		}
		
		public EmbassyDataDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public EmbassyDataDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public EmbassyDataDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public EmbassyDataDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<Customer> Customers
		{
			get
			{
				return this.GetTable<Customer>();
			}
		}
		
		public System.Data.Linq.Table<CustomerFile> CustomerFiles
		{
			get
			{
				return this.GetTable<CustomerFile>();
			}
		}
		
		public System.Data.Linq.Table<Family> Families
		{
			get
			{
				return this.GetTable<Family>();
			}
		}
		
		public System.Data.Linq.Table<Kin> Kins
		{
			get
			{
				return this.GetTable<Kin>();
			}
		}
		
		public System.Data.Linq.Table<Opr> Oprs
		{
			get
			{
				return this.GetTable<Opr>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Customer")]
	public partial class Customer : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _NationalID;
		
		private string _FName;
		
		private string _MName;
		
		private string _LName;
		
		private string _BPlace;
		
		private System.Nullable<System.DateTime> _BDate;
		
		private string _Sex;
		
		private string _Height;
		
		private string _UAgeFName;
		
		private string _UAgeMName;
		
		private string _UAgeLName;
		
		private string _EriPassportNo;
		
		private string _EriPassportType;
		
		private string _OtherPassportNo;
		
		private string _Country;
		
		private string _Type;
		
		private string _Address;
		
		private string _PhoneNo;
		
		private string _FaxNo;
		
		private string _emailAdd;
		
		private string _EEO;
		
		private string _UserName;
		
		private string _Status;
		
		private System.Nullable<System.DateTime> _StatusDate;
		
		private string _DinNo;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnNationalIDChanging(string value);
    partial void OnNationalIDChanged();
    partial void OnFNameChanging(string value);
    partial void OnFNameChanged();
    partial void OnMNameChanging(string value);
    partial void OnMNameChanged();
    partial void OnLNameChanging(string value);
    partial void OnLNameChanged();
    partial void OnBPlaceChanging(string value);
    partial void OnBPlaceChanged();
    partial void OnBDateChanging(System.Nullable<System.DateTime> value);
    partial void OnBDateChanged();
    partial void OnSexChanging(string value);
    partial void OnSexChanged();
    partial void OnHeightChanging(string value);
    partial void OnHeightChanged();
    partial void OnUAgeFNameChanging(string value);
    partial void OnUAgeFNameChanged();
    partial void OnUAgeMNameChanging(string value);
    partial void OnUAgeMNameChanged();
    partial void OnUAgeLNameChanging(string value);
    partial void OnUAgeLNameChanged();
    partial void OnEriPassportNoChanging(string value);
    partial void OnEriPassportNoChanged();
    partial void OnEriPassportTypeChanging(string value);
    partial void OnEriPassportTypeChanged();
    partial void OnOtherPassportNoChanging(string value);
    partial void OnOtherPassportNoChanged();
    partial void OnCountryChanging(string value);
    partial void OnCountryChanged();
    partial void OnTypeChanging(string value);
    partial void OnTypeChanged();
    partial void OnAddressChanging(string value);
    partial void OnAddressChanged();
    partial void OnPhoneNoChanging(string value);
    partial void OnPhoneNoChanged();
    partial void OnFaxNoChanging(string value);
    partial void OnFaxNoChanged();
    partial void OnemailAddChanging(string value);
    partial void OnemailAddChanged();
    partial void OnEEOChanging(string value);
    partial void OnEEOChanged();
    partial void OnUserNameChanging(string value);
    partial void OnUserNameChanged();
    partial void OnStatusChanging(string value);
    partial void OnStatusChanged();
    partial void OnStatusDateChanging(System.Nullable<System.DateTime> value);
    partial void OnStatusDateChanged();
    partial void OnDinNoChanging(string value);
    partial void OnDinNoChanged();
    #endregion
		
		public Customer()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NationalID", DbType="Char(15) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string NationalID
		{
			get
			{
				return this._NationalID;
			}
			set
			{
				if ((this._NationalID != value))
				{
					this.OnNationalIDChanging(value);
					this.SendPropertyChanging();
					this._NationalID = value;
					this.SendPropertyChanged("NationalID");
					this.OnNationalIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FName", DbType="NVarChar(20)")]
		public string FName
		{
			get
			{
				return this._FName;
			}
			set
			{
				if ((this._FName != value))
				{
					this.OnFNameChanging(value);
					this.SendPropertyChanging();
					this._FName = value;
					this.SendPropertyChanged("FName");
					this.OnFNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MName", DbType="NVarChar(20)")]
		public string MName
		{
			get
			{
				return this._MName;
			}
			set
			{
				if ((this._MName != value))
				{
					this.OnMNameChanging(value);
					this.SendPropertyChanging();
					this._MName = value;
					this.SendPropertyChanged("MName");
					this.OnMNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LName", DbType="NVarChar(20)")]
		public string LName
		{
			get
			{
				return this._LName;
			}
			set
			{
				if ((this._LName != value))
				{
					this.OnLNameChanging(value);
					this.SendPropertyChanging();
					this._LName = value;
					this.SendPropertyChanged("LName");
					this.OnLNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BPlace", DbType="NVarChar(20)")]
		public string BPlace
		{
			get
			{
				return this._BPlace;
			}
			set
			{
				if ((this._BPlace != value))
				{
					this.OnBPlaceChanging(value);
					this.SendPropertyChanging();
					this._BPlace = value;
					this.SendPropertyChanged("BPlace");
					this.OnBPlaceChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BDate", DbType="Date")]
		public System.Nullable<System.DateTime> BDate
		{
			get
			{
				return this._BDate;
			}
			set
			{
				if ((this._BDate != value))
				{
					this.OnBDateChanging(value);
					this.SendPropertyChanging();
					this._BDate = value;
					this.SendPropertyChanged("BDate");
					this.OnBDateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Sex", DbType="Char(6)")]
		public string Sex
		{
			get
			{
				return this._Sex;
			}
			set
			{
				if ((this._Sex != value))
				{
					this.OnSexChanging(value);
					this.SendPropertyChanging();
					this._Sex = value;
					this.SendPropertyChanged("Sex");
					this.OnSexChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Height", DbType="VarChar(50)")]
		public string Height
		{
			get
			{
				return this._Height;
			}
			set
			{
				if ((this._Height != value))
				{
					this.OnHeightChanging(value);
					this.SendPropertyChanging();
					this._Height = value;
					this.SendPropertyChanged("Height");
					this.OnHeightChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UAgeFName", DbType="NVarChar(20)")]
		public string UAgeFName
		{
			get
			{
				return this._UAgeFName;
			}
			set
			{
				if ((this._UAgeFName != value))
				{
					this.OnUAgeFNameChanging(value);
					this.SendPropertyChanging();
					this._UAgeFName = value;
					this.SendPropertyChanged("UAgeFName");
					this.OnUAgeFNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UAgeMName", DbType="NVarChar(20)")]
		public string UAgeMName
		{
			get
			{
				return this._UAgeMName;
			}
			set
			{
				if ((this._UAgeMName != value))
				{
					this.OnUAgeMNameChanging(value);
					this.SendPropertyChanging();
					this._UAgeMName = value;
					this.SendPropertyChanged("UAgeMName");
					this.OnUAgeMNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UAgeLName", DbType="NVarChar(20)")]
		public string UAgeLName
		{
			get
			{
				return this._UAgeLName;
			}
			set
			{
				if ((this._UAgeLName != value))
				{
					this.OnUAgeLNameChanging(value);
					this.SendPropertyChanging();
					this._UAgeLName = value;
					this.SendPropertyChanged("UAgeLName");
					this.OnUAgeLNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EriPassportNo", DbType="Char(10)")]
		public string EriPassportNo
		{
			get
			{
				return this._EriPassportNo;
			}
			set
			{
				if ((this._EriPassportNo != value))
				{
					this.OnEriPassportNoChanging(value);
					this.SendPropertyChanging();
					this._EriPassportNo = value;
					this.SendPropertyChanged("EriPassportNo");
					this.OnEriPassportNoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EriPassportType", DbType="VarChar(10)")]
		public string EriPassportType
		{
			get
			{
				return this._EriPassportType;
			}
			set
			{
				if ((this._EriPassportType != value))
				{
					this.OnEriPassportTypeChanging(value);
					this.SendPropertyChanging();
					this._EriPassportType = value;
					this.SendPropertyChanged("EriPassportType");
					this.OnEriPassportTypeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_OtherPassportNo", DbType="VarChar(10)")]
		public string OtherPassportNo
		{
			get
			{
				return this._OtherPassportNo;
			}
			set
			{
				if ((this._OtherPassportNo != value))
				{
					this.OnOtherPassportNoChanging(value);
					this.SendPropertyChanging();
					this._OtherPassportNo = value;
					this.SendPropertyChanged("OtherPassportNo");
					this.OnOtherPassportNoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Country", DbType="VarChar(30)")]
		public string Country
		{
			get
			{
				return this._Country;
			}
			set
			{
				if ((this._Country != value))
				{
					this.OnCountryChanging(value);
					this.SendPropertyChanging();
					this._Country = value;
					this.SendPropertyChanged("Country");
					this.OnCountryChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Type", DbType="VarChar(15)")]
		public string Type
		{
			get
			{
				return this._Type;
			}
			set
			{
				if ((this._Type != value))
				{
					this.OnTypeChanging(value);
					this.SendPropertyChanging();
					this._Type = value;
					this.SendPropertyChanged("Type");
					this.OnTypeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Address", DbType="VarChar(50)")]
		public string Address
		{
			get
			{
				return this._Address;
			}
			set
			{
				if ((this._Address != value))
				{
					this.OnAddressChanging(value);
					this.SendPropertyChanging();
					this._Address = value;
					this.SendPropertyChanged("Address");
					this.OnAddressChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PhoneNo", DbType="VarChar(15)")]
		public string PhoneNo
		{
			get
			{
				return this._PhoneNo;
			}
			set
			{
				if ((this._PhoneNo != value))
				{
					this.OnPhoneNoChanging(value);
					this.SendPropertyChanging();
					this._PhoneNo = value;
					this.SendPropertyChanged("PhoneNo");
					this.OnPhoneNoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FaxNo", DbType="Char(15)")]
		public string FaxNo
		{
			get
			{
				return this._FaxNo;
			}
			set
			{
				if ((this._FaxNo != value))
				{
					this.OnFaxNoChanging(value);
					this.SendPropertyChanging();
					this._FaxNo = value;
					this.SendPropertyChanged("FaxNo");
					this.OnFaxNoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_emailAdd", DbType="VarChar(50)")]
		public string emailAdd
		{
			get
			{
				return this._emailAdd;
			}
			set
			{
				if ((this._emailAdd != value))
				{
					this.OnemailAddChanging(value);
					this.SendPropertyChanging();
					this._emailAdd = value;
					this.SendPropertyChanged("emailAdd");
					this.OnemailAddChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EEO", DbType="VarChar(50)")]
		public string EEO
		{
			get
			{
				return this._EEO;
			}
			set
			{
				if ((this._EEO != value))
				{
					this.OnEEOChanging(value);
					this.SendPropertyChanging();
					this._EEO = value;
					this.SendPropertyChanged("EEO");
					this.OnEEOChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UserName", DbType="VarChar(50)")]
		public string UserName
		{
			get
			{
				return this._UserName;
			}
			set
			{
				if ((this._UserName != value))
				{
					this.OnUserNameChanging(value);
					this.SendPropertyChanging();
					this._UserName = value;
					this.SendPropertyChanged("UserName");
					this.OnUserNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Status", DbType="VarChar(50)")]
		public string Status
		{
			get
			{
				return this._Status;
			}
			set
			{
				if ((this._Status != value))
				{
					this.OnStatusChanging(value);
					this.SendPropertyChanging();
					this._Status = value;
					this.SendPropertyChanged("Status");
					this.OnStatusChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_StatusDate", DbType="Date")]
		public System.Nullable<System.DateTime> StatusDate
		{
			get
			{
				return this._StatusDate;
			}
			set
			{
				if ((this._StatusDate != value))
				{
					this.OnStatusDateChanging(value);
					this.SendPropertyChanging();
					this._StatusDate = value;
					this.SendPropertyChanged("StatusDate");
					this.OnStatusDateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DinNo", DbType="VarChar(50)")]
		public string DinNo
		{
			get
			{
				return this._DinNo;
			}
			set
			{
				if ((this._DinNo != value))
				{
					this.OnDinNoChanging(value);
					this.SendPropertyChanging();
					this._DinNo = value;
					this.SendPropertyChanged("DinNo");
					this.OnDinNoChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.CustomerFile")]
	public partial class CustomerFile : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _RegID;
		
		private string _FName;
		
		private string _MName;
		
		private string _LName;
		
		private System.Nullable<System.DateTime> _BDate;
		
		private string _BPlace;
		
		private string _Sex;
		
		private string _PassportNo;
		
		private string _Phone;
		
		private string _Address;
		
		private string _Email;
		
		private string _Occupation;
		
		private string _Profession;
		
		private System.Nullable<System.DateTime> _DateFromEritrea;
		
		private System.Nullable<System.DateTime> _DateToUganda;
		
		private string _MaritalStatus;
		
		private string _MotherName;
		
		private string _Education;
		
		private string _ExitMeans;
		
		private string _WorkPermit;
		
		private System.Data.Linq.Binary _Photo;
		
		private string _Officer;
		
		private System.Nullable<int> _FileNo;
		
		private string _FileStatus;
		
		private System.Nullable<System.DateTime> _RegDate;
		
		private string _OprID;
		
		private System.Nullable<bool> _Confirmed;
		
		private EntitySet<Family> _Families;
		
		private EntityRef<Kin> _Kin;
		
		private EntityRef<Opr> _Opr;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnRegIDChanging(string value);
    partial void OnRegIDChanged();
    partial void OnFNameChanging(string value);
    partial void OnFNameChanged();
    partial void OnMNameChanging(string value);
    partial void OnMNameChanged();
    partial void OnLNameChanging(string value);
    partial void OnLNameChanged();
    partial void OnBDateChanging(System.Nullable<System.DateTime> value);
    partial void OnBDateChanged();
    partial void OnBPlaceChanging(string value);
    partial void OnBPlaceChanged();
    partial void OnSexChanging(string value);
    partial void OnSexChanged();
    partial void OnPassportNoChanging(string value);
    partial void OnPassportNoChanged();
    partial void OnPhoneChanging(string value);
    partial void OnPhoneChanged();
    partial void OnAddressChanging(string value);
    partial void OnAddressChanged();
    partial void OnEmailChanging(string value);
    partial void OnEmailChanged();
    partial void OnOccupationChanging(string value);
    partial void OnOccupationChanged();
    partial void OnProfessionChanging(string value);
    partial void OnProfessionChanged();
    partial void OnDateFromEritreaChanging(System.Nullable<System.DateTime> value);
    partial void OnDateFromEritreaChanged();
    partial void OnDateToUgandaChanging(System.Nullable<System.DateTime> value);
    partial void OnDateToUgandaChanged();
    partial void OnMaritalStatusChanging(string value);
    partial void OnMaritalStatusChanged();
    partial void OnMotherNameChanging(string value);
    partial void OnMotherNameChanged();
    partial void OnEducationChanging(string value);
    partial void OnEducationChanged();
    partial void OnExitMeansChanging(string value);
    partial void OnExitMeansChanged();
    partial void OnWorkPermitChanging(string value);
    partial void OnWorkPermitChanged();
    partial void OnPhotoChanging(System.Data.Linq.Binary value);
    partial void OnPhotoChanged();
    partial void OnOfficerChanging(string value);
    partial void OnOfficerChanged();
    partial void OnFileNoChanging(System.Nullable<int> value);
    partial void OnFileNoChanged();
    partial void OnFileStatusChanging(string value);
    partial void OnFileStatusChanged();
    partial void OnRegDateChanging(System.Nullable<System.DateTime> value);
    partial void OnRegDateChanged();
    partial void OnOprIDChanging(string value);
    partial void OnOprIDChanged();
    partial void OnConfirmedChanging(System.Nullable<bool> value);
    partial void OnConfirmedChanged();
    #endregion
		
		public CustomerFile()
		{
			this._Families = new EntitySet<Family>(new Action<Family>(this.attach_Families), new Action<Family>(this.detach_Families));
			this._Kin = default(EntityRef<Kin>);
			this._Opr = default(EntityRef<Opr>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_RegID", DbType="Char(15) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string RegID
		{
			get
			{
				return this._RegID;
			}
			set
			{
				if ((this._RegID != value))
				{
					this.OnRegIDChanging(value);
					this.SendPropertyChanging();
					this._RegID = value;
					this.SendPropertyChanged("RegID");
					this.OnRegIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FName", DbType="NVarChar(20)")]
		public string FName
		{
			get
			{
				return this._FName;
			}
			set
			{
				if ((this._FName != value))
				{
					this.OnFNameChanging(value);
					this.SendPropertyChanging();
					this._FName = value;
					this.SendPropertyChanged("FName");
					this.OnFNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MName", DbType="NVarChar(20)")]
		public string MName
		{
			get
			{
				return this._MName;
			}
			set
			{
				if ((this._MName != value))
				{
					this.OnMNameChanging(value);
					this.SendPropertyChanging();
					this._MName = value;
					this.SendPropertyChanged("MName");
					this.OnMNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LName", DbType="NVarChar(20)")]
		public string LName
		{
			get
			{
				return this._LName;
			}
			set
			{
				if ((this._LName != value))
				{
					this.OnLNameChanging(value);
					this.SendPropertyChanging();
					this._LName = value;
					this.SendPropertyChanged("LName");
					this.OnLNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BDate", DbType="Date")]
		public System.Nullable<System.DateTime> BDate
		{
			get
			{
				return this._BDate;
			}
			set
			{
				if ((this._BDate != value))
				{
					this.OnBDateChanging(value);
					this.SendPropertyChanging();
					this._BDate = value;
					this.SendPropertyChanged("BDate");
					this.OnBDateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BPlace", DbType="NVarChar(20)")]
		public string BPlace
		{
			get
			{
				return this._BPlace;
			}
			set
			{
				if ((this._BPlace != value))
				{
					this.OnBPlaceChanging(value);
					this.SendPropertyChanging();
					this._BPlace = value;
					this.SendPropertyChanged("BPlace");
					this.OnBPlaceChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Sex", DbType="NChar(6)")]
		public string Sex
		{
			get
			{
				return this._Sex;
			}
			set
			{
				if ((this._Sex != value))
				{
					this.OnSexChanging(value);
					this.SendPropertyChanging();
					this._Sex = value;
					this.SendPropertyChanged("Sex");
					this.OnSexChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PassportNo", DbType="Char(10)")]
		public string PassportNo
		{
			get
			{
				return this._PassportNo;
			}
			set
			{
				if ((this._PassportNo != value))
				{
					this.OnPassportNoChanging(value);
					this.SendPropertyChanging();
					this._PassportNo = value;
					this.SendPropertyChanged("PassportNo");
					this.OnPassportNoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Phone", DbType="VarChar(15)")]
		public string Phone
		{
			get
			{
				return this._Phone;
			}
			set
			{
				if ((this._Phone != value))
				{
					this.OnPhoneChanging(value);
					this.SendPropertyChanging();
					this._Phone = value;
					this.SendPropertyChanged("Phone");
					this.OnPhoneChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Address", DbType="NVarChar(50)")]
		public string Address
		{
			get
			{
				return this._Address;
			}
			set
			{
				if ((this._Address != value))
				{
					this.OnAddressChanging(value);
					this.SendPropertyChanging();
					this._Address = value;
					this.SendPropertyChanged("Address");
					this.OnAddressChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Email", DbType="VarChar(50)")]
		public string Email
		{
			get
			{
				return this._Email;
			}
			set
			{
				if ((this._Email != value))
				{
					this.OnEmailChanging(value);
					this.SendPropertyChanging();
					this._Email = value;
					this.SendPropertyChanged("Email");
					this.OnEmailChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Occupation", DbType="NVarChar(50)")]
		public string Occupation
		{
			get
			{
				return this._Occupation;
			}
			set
			{
				if ((this._Occupation != value))
				{
					this.OnOccupationChanging(value);
					this.SendPropertyChanging();
					this._Occupation = value;
					this.SendPropertyChanged("Occupation");
					this.OnOccupationChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Profession", DbType="NVarChar(50)")]
		public string Profession
		{
			get
			{
				return this._Profession;
			}
			set
			{
				if ((this._Profession != value))
				{
					this.OnProfessionChanging(value);
					this.SendPropertyChanging();
					this._Profession = value;
					this.SendPropertyChanged("Profession");
					this.OnProfessionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DateFromEritrea", DbType="Date")]
		public System.Nullable<System.DateTime> DateFromEritrea
		{
			get
			{
				return this._DateFromEritrea;
			}
			set
			{
				if ((this._DateFromEritrea != value))
				{
					this.OnDateFromEritreaChanging(value);
					this.SendPropertyChanging();
					this._DateFromEritrea = value;
					this.SendPropertyChanged("DateFromEritrea");
					this.OnDateFromEritreaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DateToUganda", DbType="Date")]
		public System.Nullable<System.DateTime> DateToUganda
		{
			get
			{
				return this._DateToUganda;
			}
			set
			{
				if ((this._DateToUganda != value))
				{
					this.OnDateToUgandaChanging(value);
					this.SendPropertyChanging();
					this._DateToUganda = value;
					this.SendPropertyChanged("DateToUganda");
					this.OnDateToUgandaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaritalStatus", DbType="NVarChar(50)")]
		public string MaritalStatus
		{
			get
			{
				return this._MaritalStatus;
			}
			set
			{
				if ((this._MaritalStatus != value))
				{
					this.OnMaritalStatusChanging(value);
					this.SendPropertyChanging();
					this._MaritalStatus = value;
					this.SendPropertyChanged("MaritalStatus");
					this.OnMaritalStatusChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MotherName", DbType="NVarChar(50)")]
		public string MotherName
		{
			get
			{
				return this._MotherName;
			}
			set
			{
				if ((this._MotherName != value))
				{
					this.OnMotherNameChanging(value);
					this.SendPropertyChanging();
					this._MotherName = value;
					this.SendPropertyChanged("MotherName");
					this.OnMotherNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Education", DbType="NVarChar(50)")]
		public string Education
		{
			get
			{
				return this._Education;
			}
			set
			{
				if ((this._Education != value))
				{
					this.OnEducationChanging(value);
					this.SendPropertyChanging();
					this._Education = value;
					this.SendPropertyChanged("Education");
					this.OnEducationChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ExitMeans", DbType="NVarChar(50)")]
		public string ExitMeans
		{
			get
			{
				return this._ExitMeans;
			}
			set
			{
				if ((this._ExitMeans != value))
				{
					this.OnExitMeansChanging(value);
					this.SendPropertyChanging();
					this._ExitMeans = value;
					this.SendPropertyChanged("ExitMeans");
					this.OnExitMeansChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_WorkPermit", DbType="VarChar(20)")]
		public string WorkPermit
		{
			get
			{
				return this._WorkPermit;
			}
			set
			{
				if ((this._WorkPermit != value))
				{
					this.OnWorkPermitChanging(value);
					this.SendPropertyChanging();
					this._WorkPermit = value;
					this.SendPropertyChanged("WorkPermit");
					this.OnWorkPermitChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Photo", DbType="VarBinary(MAX)", UpdateCheck=UpdateCheck.Never)]
		public System.Data.Linq.Binary Photo
		{
			get
			{
				return this._Photo;
			}
			set
			{
				if ((this._Photo != value))
				{
					this.OnPhotoChanging(value);
					this.SendPropertyChanging();
					this._Photo = value;
					this.SendPropertyChanged("Photo");
					this.OnPhotoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Officer", DbType="NVarChar(MAX)")]
		public string Officer
		{
			get
			{
				return this._Officer;
			}
			set
			{
				if ((this._Officer != value))
				{
					this.OnOfficerChanging(value);
					this.SendPropertyChanging();
					this._Officer = value;
					this.SendPropertyChanged("Officer");
					this.OnOfficerChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FileNo", DbType="Int")]
		public System.Nullable<int> FileNo
		{
			get
			{
				return this._FileNo;
			}
			set
			{
				if ((this._FileNo != value))
				{
					this.OnFileNoChanging(value);
					this.SendPropertyChanging();
					this._FileNo = value;
					this.SendPropertyChanged("FileNo");
					this.OnFileNoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FileStatus", DbType="VarChar(20)")]
		public string FileStatus
		{
			get
			{
				return this._FileStatus;
			}
			set
			{
				if ((this._FileStatus != value))
				{
					this.OnFileStatusChanging(value);
					this.SendPropertyChanging();
					this._FileStatus = value;
					this.SendPropertyChanged("FileStatus");
					this.OnFileStatusChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_RegDate", DbType="Date")]
		public System.Nullable<System.DateTime> RegDate
		{
			get
			{
				return this._RegDate;
			}
			set
			{
				if ((this._RegDate != value))
				{
					this.OnRegDateChanging(value);
					this.SendPropertyChanging();
					this._RegDate = value;
					this.SendPropertyChanged("RegDate");
					this.OnRegDateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_OprID", DbType="Char(11)")]
		public string OprID
		{
			get
			{
				return this._OprID;
			}
			set
			{
				if ((this._OprID != value))
				{
					if (this._Opr.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnOprIDChanging(value);
					this.SendPropertyChanging();
					this._OprID = value;
					this.SendPropertyChanged("OprID");
					this.OnOprIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Confirmed", DbType="Bit")]
		public System.Nullable<bool> Confirmed
		{
			get
			{
				return this._Confirmed;
			}
			set
			{
				if ((this._Confirmed != value))
				{
					this.OnConfirmedChanging(value);
					this.SendPropertyChanging();
					this._Confirmed = value;
					this.SendPropertyChanged("Confirmed");
					this.OnConfirmedChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="CustomerFile_Family", Storage="_Families", ThisKey="RegID", OtherKey="RegID")]
		public EntitySet<Family> Families
		{
			get
			{
				return this._Families;
			}
			set
			{
				this._Families.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="CustomerFile_Kin", Storage="_Kin", ThisKey="RegID", OtherKey="RegID", IsUnique=true, IsForeignKey=false)]
		public Kin Kin
		{
			get
			{
				return this._Kin.Entity;
			}
			set
			{
				Kin previousValue = this._Kin.Entity;
				if (((previousValue != value) 
							|| (this._Kin.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Kin.Entity = null;
						previousValue.CustomerFile = null;
					}
					this._Kin.Entity = value;
					if ((value != null))
					{
						value.CustomerFile = this;
					}
					this.SendPropertyChanged("Kin");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Opr_CustomerFile", Storage="_Opr", ThisKey="OprID", OtherKey="OprID", IsForeignKey=true)]
		public Opr Opr
		{
			get
			{
				return this._Opr.Entity;
			}
			set
			{
				Opr previousValue = this._Opr.Entity;
				if (((previousValue != value) 
							|| (this._Opr.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Opr.Entity = null;
						previousValue.CustomerFiles.Remove(this);
					}
					this._Opr.Entity = value;
					if ((value != null))
					{
						value.CustomerFiles.Add(this);
						this._OprID = value.OprID;
					}
					else
					{
						this._OprID = default(string);
					}
					this.SendPropertyChanged("Opr");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_Families(Family entity)
		{
			this.SendPropertyChanging();
			entity.CustomerFile = this;
		}
		
		private void detach_Families(Family entity)
		{
			this.SendPropertyChanging();
			entity.CustomerFile = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Family")]
	public partial class Family : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _FamilyID;
		
		private string _RegID;
		
		private string _Name;
		
		private System.Nullable<System.DateTime> _BDate;
		
		private string _BPlace;
		
		private string _Sex;
		
		private string _Relationship;
		
		private string _OprID;
		
		private EntityRef<CustomerFile> _CustomerFile;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnFamilyIDChanging(int value);
    partial void OnFamilyIDChanged();
    partial void OnRegIDChanging(string value);
    partial void OnRegIDChanged();
    partial void OnNameChanging(string value);
    partial void OnNameChanged();
    partial void OnBDateChanging(System.Nullable<System.DateTime> value);
    partial void OnBDateChanged();
    partial void OnBPlaceChanging(string value);
    partial void OnBPlaceChanged();
    partial void OnSexChanging(string value);
    partial void OnSexChanged();
    partial void OnRelationshipChanging(string value);
    partial void OnRelationshipChanged();
    partial void OnOprIDChanging(string value);
    partial void OnOprIDChanged();
    #endregion
		
		public Family()
		{
			this._CustomerFile = default(EntityRef<CustomerFile>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FamilyID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int FamilyID
		{
			get
			{
				return this._FamilyID;
			}
			set
			{
				if ((this._FamilyID != value))
				{
					this.OnFamilyIDChanging(value);
					this.SendPropertyChanging();
					this._FamilyID = value;
					this.SendPropertyChanged("FamilyID");
					this.OnFamilyIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_RegID", DbType="Char(15)")]
		public string RegID
		{
			get
			{
				return this._RegID;
			}
			set
			{
				if ((this._RegID != value))
				{
					if (this._CustomerFile.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnRegIDChanging(value);
					this.SendPropertyChanging();
					this._RegID = value;
					this.SendPropertyChanged("RegID");
					this.OnRegIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Name", DbType="VarChar(50)")]
		public string Name
		{
			get
			{
				return this._Name;
			}
			set
			{
				if ((this._Name != value))
				{
					this.OnNameChanging(value);
					this.SendPropertyChanging();
					this._Name = value;
					this.SendPropertyChanged("Name");
					this.OnNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BDate", DbType="Date")]
		public System.Nullable<System.DateTime> BDate
		{
			get
			{
				return this._BDate;
			}
			set
			{
				if ((this._BDate != value))
				{
					this.OnBDateChanging(value);
					this.SendPropertyChanging();
					this._BDate = value;
					this.SendPropertyChanged("BDate");
					this.OnBDateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BPlace", DbType="VarChar(20)")]
		public string BPlace
		{
			get
			{
				return this._BPlace;
			}
			set
			{
				if ((this._BPlace != value))
				{
					this.OnBPlaceChanging(value);
					this.SendPropertyChanging();
					this._BPlace = value;
					this.SendPropertyChanged("BPlace");
					this.OnBPlaceChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Sex", DbType="Char(5)")]
		public string Sex
		{
			get
			{
				return this._Sex;
			}
			set
			{
				if ((this._Sex != value))
				{
					this.OnSexChanging(value);
					this.SendPropertyChanging();
					this._Sex = value;
					this.SendPropertyChanged("Sex");
					this.OnSexChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Relationship", DbType="VarChar(20)")]
		public string Relationship
		{
			get
			{
				return this._Relationship;
			}
			set
			{
				if ((this._Relationship != value))
				{
					this.OnRelationshipChanging(value);
					this.SendPropertyChanging();
					this._Relationship = value;
					this.SendPropertyChanged("Relationship");
					this.OnRelationshipChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_OprID", DbType="Char(11)")]
		public string OprID
		{
			get
			{
				return this._OprID;
			}
			set
			{
				if ((this._OprID != value))
				{
					this.OnOprIDChanging(value);
					this.SendPropertyChanging();
					this._OprID = value;
					this.SendPropertyChanged("OprID");
					this.OnOprIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="CustomerFile_Family", Storage="_CustomerFile", ThisKey="RegID", OtherKey="RegID", IsForeignKey=true, DeleteRule="CASCADE")]
		public CustomerFile CustomerFile
		{
			get
			{
				return this._CustomerFile.Entity;
			}
			set
			{
				CustomerFile previousValue = this._CustomerFile.Entity;
				if (((previousValue != value) 
							|| (this._CustomerFile.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._CustomerFile.Entity = null;
						previousValue.Families.Remove(this);
					}
					this._CustomerFile.Entity = value;
					if ((value != null))
					{
						value.Families.Add(this);
						this._RegID = value.RegID;
					}
					else
					{
						this._RegID = default(string);
					}
					this.SendPropertyChanged("CustomerFile");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Kin")]
	public partial class Kin : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _RegID;
		
		private System.Nullable<int> _KinID;
		
		private string _Name;
		
		private string _Phone;
		
		private string _Address;
		
		private string _Relationship;
		
		private EntityRef<CustomerFile> _CustomerFile;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnRegIDChanging(string value);
    partial void OnRegIDChanged();
    partial void OnKinIDChanging(System.Nullable<int> value);
    partial void OnKinIDChanged();
    partial void OnNameChanging(string value);
    partial void OnNameChanged();
    partial void OnPhoneChanging(string value);
    partial void OnPhoneChanged();
    partial void OnAddressChanging(string value);
    partial void OnAddressChanged();
    partial void OnRelationshipChanging(string value);
    partial void OnRelationshipChanged();
    #endregion
		
		public Kin()
		{
			this._CustomerFile = default(EntityRef<CustomerFile>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_RegID", DbType="Char(15) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string RegID
		{
			get
			{
				return this._RegID;
			}
			set
			{
				if ((this._RegID != value))
				{
					if (this._CustomerFile.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnRegIDChanging(value);
					this.SendPropertyChanging();
					this._RegID = value;
					this.SendPropertyChanged("RegID");
					this.OnRegIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_KinID", DbType="Int")]
		public System.Nullable<int> KinID
		{
			get
			{
				return this._KinID;
			}
			set
			{
				if ((this._KinID != value))
				{
					this.OnKinIDChanging(value);
					this.SendPropertyChanging();
					this._KinID = value;
					this.SendPropertyChanged("KinID");
					this.OnKinIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Name", DbType="VarChar(20)")]
		public string Name
		{
			get
			{
				return this._Name;
			}
			set
			{
				if ((this._Name != value))
				{
					this.OnNameChanging(value);
					this.SendPropertyChanging();
					this._Name = value;
					this.SendPropertyChanged("Name");
					this.OnNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Phone", DbType="Char(15)")]
		public string Phone
		{
			get
			{
				return this._Phone;
			}
			set
			{
				if ((this._Phone != value))
				{
					this.OnPhoneChanging(value);
					this.SendPropertyChanging();
					this._Phone = value;
					this.SendPropertyChanged("Phone");
					this.OnPhoneChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Address", DbType="VarChar(20)")]
		public string Address
		{
			get
			{
				return this._Address;
			}
			set
			{
				if ((this._Address != value))
				{
					this.OnAddressChanging(value);
					this.SendPropertyChanging();
					this._Address = value;
					this.SendPropertyChanged("Address");
					this.OnAddressChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Relationship", DbType="VarChar(20)")]
		public string Relationship
		{
			get
			{
				return this._Relationship;
			}
			set
			{
				if ((this._Relationship != value))
				{
					this.OnRelationshipChanging(value);
					this.SendPropertyChanging();
					this._Relationship = value;
					this.SendPropertyChanged("Relationship");
					this.OnRelationshipChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="CustomerFile_Kin", Storage="_CustomerFile", ThisKey="RegID", OtherKey="RegID", IsForeignKey=true, DeleteOnNull=true, DeleteRule="CASCADE")]
		public CustomerFile CustomerFile
		{
			get
			{
				return this._CustomerFile.Entity;
			}
			set
			{
				CustomerFile previousValue = this._CustomerFile.Entity;
				if (((previousValue != value) 
							|| (this._CustomerFile.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._CustomerFile.Entity = null;
						previousValue.Kin = null;
					}
					this._CustomerFile.Entity = value;
					if ((value != null))
					{
						value.Kin = this;
						this._RegID = value.RegID;
					}
					else
					{
						this._RegID = default(string);
					}
					this.SendPropertyChanged("CustomerFile");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Opr")]
	public partial class Opr : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _OprID;
		
		private string _FullName;
		
		private System.Nullable<System.DateTime> _StartDate;
		
		private System.Nullable<System.DateTime> _EndDate;
		
		private System.Nullable<bool> _Active;
		
		private System.Data.Linq.Binary _Password;
		
		private EntitySet<CustomerFile> _CustomerFiles;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnOprIDChanging(string value);
    partial void OnOprIDChanged();
    partial void OnFullNameChanging(string value);
    partial void OnFullNameChanged();
    partial void OnStartDateChanging(System.Nullable<System.DateTime> value);
    partial void OnStartDateChanged();
    partial void OnEndDateChanging(System.Nullable<System.DateTime> value);
    partial void OnEndDateChanged();
    partial void OnActiveChanging(System.Nullable<bool> value);
    partial void OnActiveChanged();
    partial void OnPasswordChanging(System.Data.Linq.Binary value);
    partial void OnPasswordChanged();
    #endregion
		
		public Opr()
		{
			this._CustomerFiles = new EntitySet<CustomerFile>(new Action<CustomerFile>(this.attach_CustomerFiles), new Action<CustomerFile>(this.detach_CustomerFiles));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_OprID", DbType="Char(11) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string OprID
		{
			get
			{
				return this._OprID;
			}
			set
			{
				if ((this._OprID != value))
				{
					this.OnOprIDChanging(value);
					this.SendPropertyChanging();
					this._OprID = value;
					this.SendPropertyChanged("OprID");
					this.OnOprIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FullName", DbType="VarChar(50)")]
		public string FullName
		{
			get
			{
				return this._FullName;
			}
			set
			{
				if ((this._FullName != value))
				{
					this.OnFullNameChanging(value);
					this.SendPropertyChanging();
					this._FullName = value;
					this.SendPropertyChanged("FullName");
					this.OnFullNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_StartDate", DbType="Date")]
		public System.Nullable<System.DateTime> StartDate
		{
			get
			{
				return this._StartDate;
			}
			set
			{
				if ((this._StartDate != value))
				{
					this.OnStartDateChanging(value);
					this.SendPropertyChanging();
					this._StartDate = value;
					this.SendPropertyChanged("StartDate");
					this.OnStartDateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EndDate", DbType="Date")]
		public System.Nullable<System.DateTime> EndDate
		{
			get
			{
				return this._EndDate;
			}
			set
			{
				if ((this._EndDate != value))
				{
					this.OnEndDateChanging(value);
					this.SendPropertyChanging();
					this._EndDate = value;
					this.SendPropertyChanged("EndDate");
					this.OnEndDateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Active", DbType="Bit")]
		public System.Nullable<bool> Active
		{
			get
			{
				return this._Active;
			}
			set
			{
				if ((this._Active != value))
				{
					this.OnActiveChanging(value);
					this.SendPropertyChanging();
					this._Active = value;
					this.SendPropertyChanged("Active");
					this.OnActiveChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Password", DbType="Binary(50)", UpdateCheck=UpdateCheck.Never)]
		public System.Data.Linq.Binary Password
		{
			get
			{
				return this._Password;
			}
			set
			{
				if ((this._Password != value))
				{
					this.OnPasswordChanging(value);
					this.SendPropertyChanging();
					this._Password = value;
					this.SendPropertyChanged("Password");
					this.OnPasswordChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Opr_CustomerFile", Storage="_CustomerFiles", ThisKey="OprID", OtherKey="OprID")]
		public EntitySet<CustomerFile> CustomerFiles
		{
			get
			{
				return this._CustomerFiles;
			}
			set
			{
				this._CustomerFiles.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_CustomerFiles(CustomerFile entity)
		{
			this.SendPropertyChanging();
			entity.Opr = this;
		}
		
		private void detach_CustomerFiles(CustomerFile entity)
		{
			this.SendPropertyChanging();
			entity.Opr = null;
		}
	}
}
#pragma warning restore 1591
